# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyRoutine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Reusable', '~> 4.0.2'
  pod "MBCircularProgressBar"
  # Pods for MyRoutine

end
